### ISSUE TITLE
allow adding more custom meta tags

### ISSUE THREAD

**Issue by tunnckoCore** [mattdesl/simple-html-index#5]
Actually something like

``` js
(opts.custom ? opts.custom : ''),
```

right after L11.

I like and understand the idea behind this simple index, but need some meta tags like `canonical` and `viewport` for example.

**Comment by yoshuawuyts** [comment]
I think `simple-html-index` should remain as simple as possible. You can customize / add any tags you want using `hyperstream`:

``` js
const hyperstream = require('hyperstream')
const html = require('simple-html-index')

const htmls = html({ entry: 'static/bundle.js' })
const hs = hyperstream({
  head: { _appendHtml: '<meta name="viewport" content="something">' }
})

htmls.pipe(hs).pipe(process.stdout)
```

Cheers! :sparkles:

**Comment by mattdesl** [comment]
Yup agree with Yoshua. 

👍

**Comment by tunnckoCore** [comment]
Mm nope, noticed that example in readme. But don't like the ides to use whole new module for just one or two tags. This community love to do the things in the hard and wrong way.

Cheers.

**Comment by mattdesl** [comment]
Sorry you feel that way.

This module is intentionally simple; trying to support every use case will increase the potential for bugs in modules and tools that have come to depend on `simple-html-index`. It increases API surface area and opens new problems:
- `custom` tells the reader nothing - why not call it `meta`? 
- does specifying `meta` replace the existing meta charset tag?
- does it append to head, or prepend? should we call it `appendMeta` for clarity, and if so, do we need `prependMeta` for parity?

It's trivial to publish another module that behaves differently and better suits your application's needs. It's also very easy to use `hyperstream` - just an extra few lines of code.

**Comment by tunnckoCore** [comment]
Yea, that's why i said "something like". And it will remain simple with one more thing.
I understand it's intentional and love this simplicity.

> It's trivial to publish another module that behaves differently and better suits your application's needs. 

Yea, but we should always try to suggest to already existing ones.

> custom tells the reader nothing - why not call it meta?

Make sense, cuz it would be for description, viewport and canonical only. And these are good things to have.
